from pydantic import BaseModel, Field
from typing import List, Optional

# What the frontend sends to our Python backend
class DeciderRequest(BaseModel):
    latitude: float
    longitude: float
    mood_input: str = Field(..., description="e.g., 'Hungover, want something spicy', 'Healthy lunch'")
    budget: Optional[str] = Field("$$", description="$, $$, $$$, or $$$$")

# A single structured recommendation generated by our AI
class RestaurantRecommendation(BaseModel):
    name: str
    cuisine: str
    reasoning: str = Field(..., description="1-sentence why this fits their mood and current weather.")
    estimated_price: str
    address: str
    rating: float

# The final payload returned to the frontend
class DeciderResponse(BaseModel):
    weather_condition: str
    recommended_vibe: str
    suggestions: List[RestaurantRecommendation]
